# Generated by Django 2.2.10 on 2020-08-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_by',
        ),
    ]
